2025-02-06T12:47:17.097Z Error: Couldn't find that app.
2025-02-06T12:47:17.101Z Error ID: not_found
2025-02-06T12:47:17.101Z     at APIHTTPClient.request (/data/data/com.termux/files/usr/lib/node_modules/heroku/node_modules/@heroku-cli/command/lib/api-client.js:174:27)
2025-02-06T12:47:17.101Z     at async GitRemote.run (/data/data/com.termux/files/usr/lib/node_modules/heroku/lib/commands/git/remote.js:17:31)
2025-02-06T12:47:17.101Z     at async GitRemote._run (/data/data/com.termux/files/usr/lib/node_modules/heroku/node_modules/@oclif/core/lib/command.js:117:22)
2025-02-06T12:47:17.101Z     at async Config.runCommand (/data/data/com.termux/files/usr/lib/node_modules/heroku/node_modules/@oclif/core/lib/config/config.js:314:25)
2025-02-06T12:47:17.101Z     at async Object.run (/data/data/com.termux/files/usr/lib/node_modules/heroku/node_modules/@oclif/core/lib/main.js:89:16)
2025/02/06 12:50:20 Error: Expected response to be successful, got 422
    at Request.handleFailure [as _handleFailure] (/data/data/com.termux/files/usr/lib/node_modules/heroku/node_modules/heroku-client/lib/request.js:255:11)
    at Request.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/heroku/node_modules/heroku-cli-util/lib/command.js:56:12)
    at /data/data/com.termux/files/usr/lib/node_modules/heroku/node_modules/heroku-client/lib/request.js:148:16
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025/02/06 12:50:20 {"id":"verification_required","message":"To create an app, verify your account by adding payment information. Verify now at https://heroku.com/verify Learn more at https://devcenter.heroku.com/articles/account-verification "}
